# BIOMECHANICS
biomech:
  T: 309.15 # Temperature (K)
  Rg: 8.314 # Universal gas constant (Pa.m^3.mol^-1.K^-1)
  delta0: 2.0e-9 # Thickness of the leaflet (m)
  Delta_: 1.4e-9 # Initial gap between the two leaflets on a non-charged membrane at equilibrium (m)
  pDelta: 1.0e5 # Attraction/repulsion pressure coefficient (Pa)
  m: 5.0 # Exponent in the repulsion term (dimensionless)
  n: 3.3 # Exponent in the attraction term (dimensionless)
  rhoL: 1075.0 # Density of the surrounding fluid (kg/m^3)
  muL: 7.0e-4 # Dynamic viscosity of the surrounding fluid (Pa.s)
  muS: 0.035 # Dynamic viscosity of the leaflet (Pa.s)
  kA: 0.24 # Area compression modulus of the leaflet (N/m)
  alpha: 7.56 # Tissue shear loss modulus frequency coefficient (Pa.s)
  C0: 0.62 # Initial gas molar concentration in the surrounding fluid (mol/m^3)
  kH: 1.613e5 # Henry's constant (Pa.m^3/mol)
  P0: 1.0e5 # Static pressure in the surrounding fluid (Pa)
  Dgl: 3.68e-9 # Diffusion coefficient of gas in the fluid (m^2/s)
  xi: 0.5e-9 # Boundary layer thickness for gas transport across leaflet (m)
  c: 1515.0 # Speed of sound in medium (m/s)

# BIOPHYSICS
biophys:
  epsilon0: 8.854e-12 # Vacuum permittivity (F/m)
  epsilonR: 1.0 # Relative permittivity of intramembrane cavity (dimensionless)
...